// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfj-iDfRcwj7tTxEuKs9OFjSQpo2dqc3o',
    appId: '1:1088486329965:web:978f35a120e9f5ef2db964',
    messagingSenderId: '1088486329965',
    projectId: 'shenith-chatapp',
    authDomain: 'shenith-chatapp.firebaseapp.com',
    storageBucket: 'shenith-chatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkdt1X_WCf3pJ7-zRAbvuRpaEnuXQ_3x4',
    appId: '1:1088486329965:android:1a502826757203b92db964',
    messagingSenderId: '1088486329965',
    projectId: 'shenith-chatapp',
    storageBucket: 'shenith-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBn3dIkBtS3Yt-yjmm75k0ewtLEVET_Ns',
    appId: '1:1088486329965:ios:2ee252230533fc362db964',
    messagingSenderId: '1088486329965',
    projectId: 'shenith-chatapp',
    storageBucket: 'shenith-chatapp.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBn3dIkBtS3Yt-yjmm75k0ewtLEVET_Ns',
    appId: '1:1088486329965:ios:85d1cb0c76f6140b2db964',
    messagingSenderId: '1088486329965',
    projectId: 'shenith-chatapp',
    storageBucket: 'shenith-chatapp.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
